name: Getting Started

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Logging Disc Space
        run: df -h
        
      - name: Step 2 - Checkout the main github branch
        uses: actions/checkout@v2
      
      - name: Step 3 - Checking python version
        run: python --version
        
      - name: Step 4 - Checking Opering-System's version and Hostname
        run: hostnamectl
  
  build-on-ubuntu:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Step 1 - Checking contents in folder
        run: python main.py
      
      - name: Step 2 - Running shell script
        run: sh ./github-actions-script.sh
