name: Getting Started

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Logging Disc Space
        run: df -h
        
      - name: Checkout the main github branch
        uses: actions/checkout@v2
      
      - name: Checking python version
        run: python --version
        
      - name: Checking Opering-System's version and Hostname
        run: hostnamectl
